/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parser_maker;

/**
 *
 * @author liviaciabati
 */
public class DataGenerator
{
     
    
    public static final String[] nomes = new String[]{"Miguel" , 
    "Davi " , 
    "Arthur" , 
    "Gabriel" , 
    "Pedro" , 
    "Lucas" , 
    "Matheus" , 
    "Bernardo" , 
    "Rafael" , 
    "Guilherme" , 
    "Enzo" , 
    "Felipe" , 
    "Gustavo" , 
    "Nicolas" , 
    "Heitor" , 
    "Samuel" , 
    "João Pedro" , 
    "Pedro Henrique" , 
    "Cauã" , 
    "Henrique" , 
    "Murilo" , 
    "Eduardo" , 
    "Vitor" , 
    "Daniel" , 
    "Lorenzo" , 
    "Vinicius" , 
    "Pietro" , 
    "João Vitor" , 
    "Leonardo" , 
    "Théo" , 
    "Caio" , 
    "Isaac" , 
    "Lucca" , 
    "João" , 
    "Davi Lucas" , 
    "Enzo Gabriel" , 
    "Yuri" , 
    "Bryan" , 
    "Thiago" , 
    "João Gabriel" , 
    "Benjamin" , 
    "Joaquim" , 
    "Emanuel" , 
    "Thomas" , 
    "Ryan" , 
    "Carlos Eduardo" , 
    "Rodrigo" , 
    "Ian" , 
    "Fernando" , 
    "Bruno" , 
    "Otávio" , 
    "Francisco" , 
    "Calebe" , 
    "Igor" , 
    "Antonio" , 
    "Erick" , 
    "João Lucas" , 
    "Luiz Felipe" , 
    "André" , 
    "Davi Lucca" , 
    "Kaique" , 
    "Nathan" , 
    "Luiz Miguel" , 
    "Breno" , 
    "Vitor Hugo" , 
    "João Guilherme" , 
    "Benício" , 
    "Augusto" , 
    "João Miguel" , 
    "Pedro Lucas" , 
    "Levi" , 
    "Anthony" , 
    "Yago" , 
    "Danilo" , 
    "Juan" , 
    "Kauê" , 
    "Diego" , 
    "Vicente" , 
    "Davi Luiz" , 
    "Luiz Gustavo" , 
    "Alexandre" , 
    "Raul" , 
    "Luan" , 
    "Diogo" , 
    "Marcelo" , 
    "Ricardo" , 
    "Luiz Henrique" , 
    "Henry" , 
    "Noah" , 
    "Enrico" , 
    "Lucas Gabriel" , 
    "Renan" , 
    "Luiz Otávio" , 
    "Pedro Miguel" , 
    "William" , 
    "Ícaro" , 
    "Giovanni" , 
    "João Paulo" , 
    "Paulo" , 
    "Sophia" , 
    "Julia" , 
    "Alice" , 
    "Manuela" , 
    "Isabella" , 
    "Laura" , 
    "Maria Eduarda" , 
    "Giovanna" , 
    "Valentina" , 
    "Beatriz" , 
    "Luiza" , 
    "Helena" , 
    "Maria Luiza" , 
    "Isadora" , 
    "Mariana" , 
    "Gabriela" , 
    "Ana Clara" , 
    "Rafaela" , 
    "Maria Clara" , 
    "Isabelly" , 
    "Yasmin" , 
    "Ana Julia" , 
    "Lívia" , 
    "Lara" , 
    "Lorena" , 
    "Heloísa" , 
    "Melissa" , 
    "Sarah" , 
    "Ana Luiza" , 
    "Letícia" , 
    "Nicole" , 
    "Ana Beatriz" , 
    "Emanuelly" , 
    "Esther" , 
    "Lavínia" , 
    "Marina" , 
    "Cecília" , 
    "Rebeca" , 
    "Vitória" , 
    "Maria Fernanda" , 
    "Larissa" , 
    "Clara" , 
    "Carolina" , 
    "Bianca" , 
    "Alícia" , 
    "Fernanda" , 
    "Gabrielly" , 
    "Catarina" , 
    "Ana Laura" , 
    "Emilly" , 
    "Eduarda" , 
    "Amanda" , 
    "Pietra" , 
    "Agatha" , 
    "Milena" , 
    "Maria Alice" , 
    "Laís" , 
    "Maria Julia" , 
    "Maria" , 
    "Elisa" , 
    "Stella" , 
    "Maria Vitória" , 
    "Bruna" , 
    "Ana Sophia" , 
    "Bárbara" , 
    "Maria Cecília" , 
    "Olivia" , 
    "Nathalia" , 
    "Camila" , 
    "Ana Carolina" , 
    "Maitê" , 
    "Eloá" , 
    "Luana" , 
    "Luna" , 
    "Ana Lívia" , 
    "Brenda" , 
    "Alana" , 
    "Sophie" , 
    "Ana" , 
    "Isabel" , 
    "Mirella" , 
    "Juliana" , 
    "Marcela" , 
    "Isis" , 
    "Iara" , 
    "Antônia" , 
    "Kamilly" , 
    "Alexia" , 
    "Lis" , 
    "Maria Sophia" , 
    "Joana" , 
    "Clarice" , 
    "Ayla" , 
    "Caroline" , 
    "Antonella" , 
    "Evellyn" , 
    "Malu" , 
    "Maria Laura" , 
    "Mikaela" , 
    "Stefany" };
}

